<?php
/**
 * Abhay
 * 
 * PHP version 7
 * 
 * @category  Abhay
 * @package   Abhay_OutOfStockSubscription
 * @author    Abhay Agrawal <abhay@gmail.com>
 * @copyright 2022 Copyright © Abhay
 * @license   See COPYING.txt for license details.
 * @link      https://github.com/abhay1198/out-of-stock-subscription
 */

$subscribedProduct = $block->getSubscribedProductCollection();
foreach ($subscribedProduct as $product)
{
    echo $product->getEmail();
    echo $product->getProductName();
}